### ISSUE TITLE
Assignment 2

### ISSUE THREAD

**Issue by dvberkel** [HAN-ASD-DT/elm-assignment-bjornvoesten#1]
In this assignment you assume that the first argument is the interval that lies most two the left. E.g. in your `hull` implementation

```elm
hull : Interval -> Interval -> Interval
hull first second =
     {
        minimal = first.minimal,
        maximal = second.maximal
}
```

What happens if the first interval is `[5,8]` and the second interval is `[1,3]`. Your  implementation would return `[5, 3]` which is not correct.

**Comment by bjornvoesten** [comment]
`
hull : Interval -> Interval -> Interval
hull first second =
     {
        minimal = min first.minimal second.minimal,
        maximal = max first.maximal second.maximal
}
`

Dit is nu mijn implementatie voor de hull. Hij pakt dus de minimale waarde van de twee intervals, de maximale waarde van de intervals, en maakt hier een nieuwe interval van.

**Comment by dvberkel** [comment]
Dit ziet er heel goed uit
